# Generated by Django 3.2.13 on 2022-04-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('log', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('infectado', models.BooleanField(default=False)),
                ('acusacoes', models.PositiveIntegerField(default=0, verbose_name='acusações')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.PositiveIntegerField(default=0, verbose_name='Água')),
                ('alimento', models.PositiveBigIntegerField(default=0)),
                ('medicacao', models.PositiveBigIntegerField(default=0, verbose_name='Medicação')),
                ('municao', models.PositiveBigIntegerField(default=0, verbose_name='Munição')),
                ('sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZSSN_app.sobrevivente')),
            ],
        ),
    ]
