# Generated by Django 3.2.13 on 2022-04-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Idade', models.PositiveIntegerField()),
                ('Sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('Log', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Infectado', models.BooleanField(default=False, editable=False)),
                ('Água', models.PositiveIntegerField(default=0)),
                ('Alimento', models.PositiveBigIntegerField(default=0)),
                ('Medicação', models.PositiveBigIntegerField(default=0)),
                ('Munição', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
