# Generated by Django 3.2.13 on 2022-04-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobrevivente',
            old_name='name',
            new_name='nome',
        ),
    ]
