# Generated by Django 3.2.13 on 2022-04-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('pontos', models.PositiveIntegerField()),
            ],
        ),
    ]
