# Generated by Django 3.2.13 on 2022-04-16 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0002_alter_inventario_alimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='sobrevivente',
        ),
        migrations.AddField(
            model_name='sobrevivente',
            name='inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ZSSN_app.inventario'),
            preserve_default=False,
        ),
    ]
