# Generated by Django 3.2.13 on 2022-04-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0002_iten'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iten',
            new_name='Item',
        ),
    ]
