# Generated by Django 3.2.13 on 2022-04-16 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0003_auto_20220415_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivente',
            name='inventario',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ZSSN_app.inventario'),
        ),
    ]
