# Generated by Django 3.2.13 on 2022-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0004_sobrevivente_acusacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='pontos',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='acusacoes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
