# Generated by Django 3.2.13 on 2022-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0005_auto_20220414_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='acusacao1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sobrevivente',
            name='acusacao2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sobrevivente',
            name='acusacao3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='acusacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
