# Generated by Django 3.2.13 on 2022-04-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0005_alter_inventario_alimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='alimento',
            new_name='alimentacao',
        ),
    ]
