# Generated by Django 3.2.13 on 2022-04-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0006_auto_20220414_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivente',
            name='Infectado',
            field=models.BooleanField(default=False),
        ),
    ]
