# Generated by Django 3.2.13 on 2022-04-16 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0006_rename_alimento_inventario_alimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='infectados_relatados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=[], size=None),
        ),
    ]
