# Generated by Django 3.2.13 on 2022-04-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0007_alter_sobrevivente_infectado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobrevivente',
            name='acusacao1',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='acusacao2',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='acusacao3',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='pontos',
        ),
    ]
