# Generated by Django 3.2.13 on 2022-04-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0008_auto_20220415_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.PositiveIntegerField(default=0)),
                ('alimento', models.PositiveBigIntegerField(default=0)),
                ('medicacao', models.PositiveBigIntegerField(default=0)),
                ('municao', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
