# Generated by Django 3.2.13 on 2022-04-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0009_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='sobrevivente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ZSSN_app.sobrevivente'),
            preserve_default=False,
        ),
    ]
