# Generated by Django 3.2.13 on 2022-04-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0010_sobrevivente_data_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobrevivente',
            name='idade',
        ),
    ]
