# Generated by Django 3.2.13 on 2022-04-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0010_inventario_sobrevivente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
