# Generated by Django 3.2.13 on 2022-04-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0011_remove_sobrevivente_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobrevivente',
            name='inventario',
        ),
        migrations.AddField(
            model_name='inventario',
            name='sobrevivente',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ZSSN_app.sobrevivente'),
            preserve_default=False,
        ),
    ]
