# Generated by Django 3.2.13 on 2022-04-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_app', '0011_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobrevivente',
            name='Alimento',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='Medicação',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='Munição',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='Água',
        ),
    ]
